hash-format = "sha256"

[[files]]
file = "LICENSE"
hash = "e3a994d82e644b03a792a930f574002658412f62407f5fee083f2555c5f23118"

[[files]]
file = "README.md"
hash = "8661e4f2780ae705d41862403b01985c5924833c386afcf490e61014f295e72f"

[[files]]
file = "config/betterf3.json"
hash = "c967de25c9263dfbd2a1086bc707446587d6071d221ba19d342206b852c97976"

[[files]]
file = "config/inventoryprofilesnext/inventoryprofiles.json"
hash = "e08ba368d2d0b105ca030c30cb0212bf989e7755c9212bb905c317f3d80d4cdf"

[[files]]
file = "config/roughlyenoughitems/config.json5"
hash = "1de69e8f68a255bfe1fcb76f413df1fac1b969ce7e58109736d3e2763b9b3b0e"

[[files]]
file = "config/xaerominimap.txt"
hash = "6a7eb713c56da42bca695cae995754b2b8c3bb43e5f107a51a6c0c734f22d048"

[[files]]
file = "config/yosbr/options.txt"
hash = "85ce684a518fe55c101d1e569681a9af2e512009221c5cd7b6b2185e44205aca"

[[files]]
file = "mods/advancementinfo.pw.toml"
hash = "b4897ff5706d7452917b6f8559210f60ae301c811a042df57df31c989e990b54"
metafile = true

[[files]]
file = "mods/animatica.pw.toml"
hash = "f0463f1b50e2c2ab3c726b14236b22e07ce9be4896528ede9d51486a212a5c07"
metafile = true

[[files]]
file = "mods/antighost.pw.toml"
hash = "59f11097c3005d5efcec93d0cd8a1ce690dc1ed65b9e56c2b1ed7bdca24cf022"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "3b3eb136a09515edaa9d3b6fba49ac2d025c1dba4a5a0d9d7fdab1e17c6bddfb"
metafile = true

[[files]]
file = "mods/auth-me.pw.toml"
hash = "d8c4f0d87acda52c94a6f341cd98db22804e934b322eda4470089e3a511e8070"
metafile = true

[[files]]
file = "mods/bad-horse-fix.pw.toml"
hash = "d450e8f7cec80312ee55ee126ee9325528882ea3fce788c81ef30dce2fb6c564"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "961a423cc427d4c785354239e8e7b251b5575756b1cf85dd1bc85011b47f0fbf"
metafile = true

[[files]]
file = "mods/better-ping-display-fabric.pw.toml"
hash = "ec31177d5cf656efdff737432455211defb8ee188749e3f53f117f75f83d1b6a"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "8b13db034aecef8d45addf4f12aa024d35b905ae144df48542683e1b162ba4f9"
metafile = true

[[files]]
file = "mods/blur-fabric.pw.toml"
hash = "fbba50d7962a2f9b75b4765b71f19e30c2864b3c863bb1b93d881d2d5c358e07"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "617563db0d44229fb65eb660130d02d1a4d2f29233eda03b68d3273e700326f8"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "33d342ee2fb724a91754eddb0124a0383cf5a8b3ce4cf5ec64aef6f55e89235e"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "7a4414a95295f22f036699300878058ddf043659fc95ac1bf1d7f725acb0bc46"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "f250d6778f5b8d03ca32913bea5ea677508e9bb6d8201cdebe005bbe9c3100ee"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "ab1c014ce67654e89af779137bdfd1f6f22888af218f44cf5d83e943d0d5fbc4"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "1a65361cf2207ba6bad6eba3e66e407983452398c4ac5cbe5db0d8430b8a6496"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "df7d79acf12a498c7d2c06c80417b14974e321aac61afa7e570b30330aedc764"
metafile = true

[[files]]
file = "mods/dynamiccrosshair.pw.toml"
hash = "0f4d0a39eb5ba73e8cd1eecb7ec6fd2fcfca53fa537a75929b691f9e903b3394"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "179d1b7ca85bd3202749e2cc95413daec331dd37dbcf66d07f12a2cd1c0ee397"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "ecd143b560c3a3206ac1005ed0664bae8902a08caea9eef6fcb06e4bb5844f46"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "307cd10b6f2fa6aa4731540f76802e8803e8e93e1cc747927ae94bc168cbcbbf"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "121cb63c8ecad9d730ecbd21000182b29a7f0e9ff8bf7645574d556a959d132d"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "3d6073b78407cf64f5f8ba7d684a626224a2d37e54ea36bfe27c8d62e5358c01"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d74850aaf1ed5a53805d523aa2b624f58c43813446be0b6c066a599c80d704e6"
metafile = true

[[files]]
file = "mods/fabricskyboxes-interop.pw.toml"
hash = "f80e4a46fab9a9c99ebf3193f2c73675f6f6659fcd740692e14501213f633c70"
metafile = true

[[files]]
file = "mods/fabricskyboxes.pw.toml"
hash = "4d979c0f0902b82fc22fc60b741d3a9ce8331de9ffcc4f54658af92ff8ff8a81"
metafile = true

[[files]]
file = "mods/fadeless.pw.toml"
hash = "bd5311680997fada18e6492a91770fdc0762c718b3109820d67c1b019c2f1bf8"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "4146027b92b4885fddec00435233c61c3728b5e09265982ab187021519a4fa89"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "bd0e1bfaa16148cd114e33d11ec8f742979ec5b9372f6baa6a335a316659e70e"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "e416b18eebf514dea2014cf5c7fd3ee8493934a0b4e937509f15172ad271fde2"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "f91f449f949d8618e231fa4a64b8715c49d13030779273cfa0b7a5f889b4c0ed"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "7169f560465ba70f204d3c4189cf3d1faef8ae6cf3dc063733a4d53f612a4d94"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "fe6abe1ea33393fe1441801f79eda74ea892e5f4b677a56eccafafcbf4d253ca"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "d398662ae6e9d87e89384ba50a9787dbeb9425902a18b0cd8239efd0b966b453"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "46775cb51714cb624ab336889c25c29945998c67b8f32f8fb11e9fb7ecf50c67"
metafile = true

[[files]]
file = "mods/lighty.pw.toml"
hash = "788e220cbcea93e3b87892f09a4b296f72993ba7ed5929195a8b7c82e7baae00"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "3dedde5213176d72e1c353877fa44315945e8f3da2ba05f5679d81e9f558bb1d"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "3c0945a312aca06a2185b00cb03ae482949b008d72614497148aa2df301af019"
metafile = true

[[files]]
file = "mods/moddetectionpreventer.pw.toml"
hash = "afab2fbd384fd1f093b7b6d1500d3227c129223b4a6e2ee62ed43b63bfae8f1d"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "6ff047f3b0e73e22bf5ad0d6751f82cd6f6a4e164a911a37839eba667fa85502"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "a05dcb27d2d7895c0ae969259d96841d689f233746595140ad8d9fc8cd9d8610"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "b61b0ccdc8328d637c0f57cbb25258491b94ae03c89c4194ad6ca8b86579dd28"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "1447b2cbf7c1d96fd410f85fdd029c1de4a4f8709d09146e602b6054065e49c0"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "ef9c4bc27256d065df4feaba2bc05883ba22987c41cd48786070d37ae85cc8e1"
metafile = true

[[files]]
file = "mods/music-control.pw.toml"
hash = "a3485113a1d1a639dfa29eb726263308cb4cd27537d6f09c1751dcff124ef396"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "a045df0a5d03ef89d92ca9318aa42a5a5e7617b37dd38d32b0a7058c0f6f4ef7"
metafile = true

[[files]]
file = "mods/no-strip.pw.toml"
hash = "64a8d5113f03e9f5931239a1f73962008e99f89b94e35a2b4daf8482d3c78f45"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "a2a38850af0076bcfb2c34327f59626d73a87876d03c4039092babfc673428c6"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "8bb727360596439b65a6bc057ccd0a51996e529948c59d41c35db05ee35ca559"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "a39b51d148022a536c3cf145dbaf84fa94c3c84b57dce82ea5e49e88bb91f756"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "0e59d00de821ce2095849c161e17e03d12a768d18859e813086adeaa71fd037b"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "975478c93b1218131fd48695cd7efb9bbe0d69125409940b015a7058e42fb6be"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
hash = "bab65e32078216683b5b01cf60d06cd01a3cd4ff1339d1b4de1091338c3b1e21"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "42e0923e98116788bdc09a174d943d81e28e0c2b3c7221eaacb839a9a9359aed"
metafile = true

[[files]]
file = "mods/screenshot-to-clipboard.pw.toml"
hash = "672f3809a2053eef01aea4015ca4b0d4be6c507622172c091c17833b8d2ffb39"
metafile = true

[[files]]
file = "mods/screenshot-viewer.pw.toml"
hash = "161d5d4d43f78ec1eeff89652fea418de615abbcf94ec8706aa318bf7d42c6c8"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "f43c022a952f3d81a8b722897a686f53de82cb953189d5eb17c4049b3fcf1727"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "f7c09e537f9db67804dd7df6b8ba3a0cfb63429ad992a99e8f8faba33187ded2"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "5e73967368d47038c38dc52fa298b45603fbe6baf2608f171638ff767178ad9a"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "84760358262cc7ab63eefbaf3dc3286f2b27497e1c5a224ea3d82f80889d17d7"
metafile = true

[[files]]
file = "mods/vivecraft.pw.toml"
hash = "029d7776be39175a6075ef310e4a42402b1b38a3c4bd3631f9d216fd87399265"
metafile = true

[[files]]
file = "mods/xaeros-minimap-fair.pw.toml"
hash = "843268e961b7325fe7e0044f1861072aa74f8e32d1ff9c01a282e7e303e4be29"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "0e64714c116db266b1c35b0fea980d0ad75ddee7639d13f89d5cedf6c7e336e7"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "6f6334f336a876088431df70e2bba6ac52ca2ddeb73a4880ce88d6954b09af00"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "af2f18c6feb48fe4bfc019bdbc4899eb874324082207dc01171ffbf15547f5dd"
metafile = true

[[files]]
file = "resourcepacks/fast-better-grass.pw.toml"
hash = "ef8b4c780a1410f45321a8f708c37a818a01ca0b576f0621e174899eb31e3853"
metafile = true

[[files]]
file = "resourcepacks/ovos-rustic-redemption.pw.toml"
hash = "b74d0f166c1abd32edd9831d5d1945ee0f343b482f5ce467a0bf3926dc5fa687"
metafile = true

[[files]]
file = "shaderpacks/bsl-shaders.pw.toml"
hash = "67b9869a6115164afaa3747142a4a971a09789b6d89d2451888ab31d7ab5bfb8"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "1e9f9f7053c256baf766dddba7a1f929634f5629c6787ae4ff1f117159232c22"
metafile = true

[[files]]
file = "shaderpacks/complementary-unbound.pw.toml"
hash = "345a368be43732e614d93ffb06fa8c76fa8f6060f2d105455242d15acc97e80d"
metafile = true
