name = "DoonCraft Vanilla+"
author = "DoonGuy"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a8b5ef181eb0211d1cb581e80d87d84d3a892e760e492a2277e6f5f8cc057af3"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
